// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package perfc_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [31:0] q;} perfc_reg2hw_prueba_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } perfc_hw2reg_prueba_reg_t;

  // Register -> HW type
  typedef struct packed {
    perfc_reg2hw_prueba_reg_t prueba;  // [31:0]
  } perfc_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    perfc_hw2reg_prueba_reg_t prueba;  // [32:0]
  } perfc_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PERFC_PRUEBA_OFFSET = 2'h0;

  // Register index
  typedef enum int {PERFC_PRUEBA} perfc_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PERFC_PERMIT[1] = '{
      4'b1111  // index[0] PERFC_PRUEBA
  };

endpackage

